package com.zhang.shop.dataObject;

import lombok.Data;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Data
@Repository
public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_name
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    private String promoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.item_id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_item_price
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    private Double promoItemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_data
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    private Date startData;
    private Date endData;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.id
     *
     * @return the value of promo.id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.id
     *
     * @param id the value for promo.id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_name
     *
     * @return the value of promo.promo_name
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_name
     *
     * @param promoName the value for promo.promo_name
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.item_id
     *
     * @return the value of promo.item_id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.item_id
     *
     * @param itemId the value for promo.item_id
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_item_price
     *
     * @return the value of promo.promo_item_price
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public Double getPromoItemPrice() {
        return promoItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_item_price
     *
     * @param promoItemPrice the value for promo.promo_item_price
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public void setPromoItemPrice(Double promoItemPrice) {
        this.promoItemPrice = promoItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.start_data
     *
     * @return the value of promo.start_data
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public Date getStartData() {
        return startData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.start_data
     *
     * @param startData the value for promo.start_data
     *
     * @mbg.generated Sun Feb 07 21:42:32 GMT+08:00 2021
     */
    public void setStartData(Date startData) {
        this.startData = startData;
    }
}